### ISSUE TITLE
Compressing the images?

### ISSUE THREAD

**Issue by Temikus** [artichoke/docker-artichoke-nightly#7]
Compressors, like `docker-slim` may yield us some gains in image size without much additional work.

Do you think it's worth it to look into it?

**Comment by lopopolo** [comment]
As I understand it, the Docker images produced during builds are very thing wrappers around the base images (2 small layers to copy the executables). I think this means the incremental cost to users pulling these images is very small since it is likely that the base image is already present in their cache.

Does using `docker-slim` rewrite the layers in the base image and make pulls more expensive in practice?

**Comment by Temikus** [comment]
Hmmm, didn't think about it in that way, I think you're right. I'll close out this issue then.
